#pragma once

#include <lvgl.h>

#include <cstdlib>

// Small MDI fonts with only the icons the tile bars show (the Lock toggle
// thumb, the Alarm modes and Disarm, the Fan thumb) and the lock of
// PIN-protected tiles (icon_lock_mark.h), generated by
// tools/generate-mdi-bar-icon-fonts.mjs. The tile's own icon keeps
// FONT_MDI_ICONS (one size per layout); scaling it down with an LVGL
// transform would draw the label through a layer on every frame.
// The fonts are C files: C linkage, also for C++ ABIs that mangle globals.
#ifdef __cplusplus
extern "C" {
#endif
LV_FONT_DECLARE(mdi_bar_icons_15);
LV_FONT_DECLARE(mdi_bar_icons_18);
LV_FONT_DECLARE(mdi_bar_icons_22);
LV_FONT_DECLARE(mdi_bar_icons_26);
LV_FONT_DECLARE(mdi_bar_icons_34);
#ifdef __cplusplus
}
#endif

namespace mdi_bar_icons {

// The font whose line is closest to 45 % of the one-row bar height
// (level_bar::BarBox::base): 22 on the 480x480 panels, 26 on the V2 and the
// 1024x600 panels, 34 on the Tab5 and the 4B.
inline const lv_font_t* for_bar(int base) {
  const lv_font_t* fonts[] = {&mdi_bar_icons_22, &mdi_bar_icons_26, &mdi_bar_icons_34};
  const int want = base * 45 / 100;
  const lv_font_t* best = fonts[0];
  for (const lv_font_t* font : fonts) {
    if (std::abs(lv_font_get_line_height(font) - want) < std::abs(lv_font_get_line_height(best) - want)) best = font;
  }
  return best;
}

}  // namespace mdi_bar_icons
